# Generated by Django 4.1.7 on 2023-03-09 13:12

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('avatar', models.ImageField(blank=True, help_text='рекомендуемый размер 600*600', null=True, upload_to='usersavatars/', verbose_name='Аватарка')),
                ('email_verify', models.BooleanField(default=False)),
                ('banned', models.CharField(choices=[('Заблокирован модератором', 'ЗАБЛОКИРОВАТЬ'), ('Не заблокирован', 'РАЗБЛОКИРОВАТЬ')], default='Не заблокирован', max_length=30, verbose_name='Забанить пользователя?')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Комментарий пользователю')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=70, unique=True, verbose_name='Название курса')),
                ('slug', models.SlugField(max_length=70, null=True, unique=True, verbose_name='URL')),
                ('annotation', models.CharField(max_length=200, verbose_name='Аннотация')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Подробное описание')),
                ('picture', models.ImageField(help_text='Рекомендуемый размер 2000*1000', upload_to='picture_courses/', verbose_name='Картинка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=70, unique=True, verbose_name='Название курса')),
                ('slug', models.SlugField(max_length=70, null=True, unique=True, verbose_name='URL')),
                ('annotation', models.CharField(max_length=200, verbose_name='Аннотация')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Подробное описание')),
                ('picture', models.ImageField(help_text='Рекомендуемый размер 2000*1000', upload_to='picture_courses/', verbose_name='Картинка')),
                ('link_move', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на видео на YouTube')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс урока')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор курса')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
