# Generated by Django 4.1.7 on 2023-03-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='customer',
        ),
    ]
