# Generated by Django 4.1.7 on 2023-03-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='link_move',
            new_name='link_movie',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер 2000*1000', null=True, upload_to='picture_courses/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер 2000*1000', null=True, upload_to='picture_courses/', verbose_name='Картинка'),
        ),
    ]
